networks:
  k6:
    driver: bridge

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.1-management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - k6
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 7s
  k6:
    container_name: k6
    image: mvolejnik/k6-with-amqp
    hostname: k6
    networks:
      - k6
    volumes:
      - type: bind
        source: ./simple.js
        target: /home/k6/simple.js
      - type: bind
        source: ./produce-consume.js
        target: /home/k6/produce-consume.js
    command: "run produce-consume.js"
    depends_on:
      rabbitmq:
        condition: service_healthy

